config/routes.rb
Rails.application.routes.draw do
  resources :credit_cards, only: %i[index create]
  get "/credit_cards/:id" => 'credit_cards#show_info'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/credit_card.rb
class CreditCard < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :email, :password, :password_confirmation])
  end

end

app/controllers/credit_cards_controller.rb
class CreditCardsController < ApplicationController
  def index
    @credit_cards = CreditCard.all
    @credit_card = CreditCard.find_by(default_for_payment: true)
  end

  def show_info
    @credit_card = CreditCard.find(params[:id])
    respond_to { |format| format.js }
  end

  private

  def credit_card_params
    params.require(:credit_card).permit(:brand, :expiration_month, :expiration_year, :default_for_payment)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/credit_cards_helper.rb
module CreditCardsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/credit_cards/_form.html.erb
<%= form_with model: @credit_card, url: credit_cards_path, local: true, class:'info' do |form| %>
  <div class='form-style'>

    <h4>Information from Credit Card</h4>

    <div class='row'>
      <div class='col'>
        <div class='form-group'>
          <%= form.label :id %>
          <%= form.text_field :id, class:'form-control' %>
        </div>
      </div>
      <div class='col'>
        <div class='form-group'>
          <%= form.label :brand %>
          <%= form.text_field :brand, class:'form-control' %>
        </div>
      </div>
    </div>

    <div class='row'>
      <div class='col'>
        <div class='form-group'>
          <%= form.label :expiration_month %>
          <%= form.text_field :expiration_month, class:'form-control' %>
        </div>
      </div>
      <div class='col'>
        <div class='form-group'>
          <%= form.label :expiration_year %>
          <%= form.text_field :expiration_year, class:'form-control' %>
        </div>
      </div>
      <div class='col'>
        <div class='form-group'>
          <%= form.label :default_for_payment %>
          <%= form.text_field :default_for_payment, class:'form-control' %>
        </div>
      </div>
    </div>
    
    <div class='actions'>
      <%= form.submit 'Salvar', class:'btn btn-primary' %>
    </div>
  </div>
<% end %>

app/views/credit_cards/_info.html.erb
<%= form_with model: @credit_card, url: credit_cards_path, local: true, class:'info' do |form| %>
  <div class='form-style'>

    <h4>Information from Credit Card</h4>

    <div class='row'>
      <div class='col'>
        <div class='form-group'>
          <%= form.label :id %>
          <%= form.text_field :id, class:'form-control' %>
        </div>
      </div>
      <div class='col'>
        <div class='form-group'>
          <%= form.label :brand %>
          <%= form.text_field :brand, class:'form-control' %>
        </div>
      </div>
    </div>

    <div class='row'>
      <div class='col'>
        <div class='form-group'>
          <%= form.label :expiration_month %>
          <%= form.text_field :expiration_month, class:'form-control' %>
        </div>
      </div>
      <div class='col'>
        <div class='form-group'>
          <%= form.label :expiration_year %>
          <%= form.text_field :expiration_year, class:'form-control' %>
        </div>
      </div>
      <div class='col'>
        <div class='form-group'>
          <%= form.label :default_for_payment %>
          <%= form.text_field :default_for_payment, class:'form-control' %>
        </div>
      </div>
    </div>
    
    <div class='actions'>
      <%= form.submit 'Salvar', class:'btn btn-primary' %>
    </div>
  </div>
<% end %>

app/views/credit_cards/index.html.erb
<b>Credit Cards</b>

<%= select_tag "credit_card", options_from_collection_for_select(@credit_cards, "id", "brand"), class:"credit_card_selection", style:"margin-bottom:20px;" %>

<div class="credit_card_info">
  <%= render partial: 'form', credit_card: @credit_card %>
</div>

<script src='https://cdnjs.cloudflare.com/ajax/libs/jquery/3.6.0/jquery.min.js'></script>

<script>
  $('.credit_card_selection').on('change', function () {
    let credit_card_id = $(this).val();
    $.ajax({
      data: {credit_card_id: credit_card_id},
      url: `/credit_cards/${credit_card_id}`,
      type: 'GET'
    });
  });
</script>

app/views/credit_cards/show_info.js.erb
$('.credit_card_info').html("<%= j(render 'info') %>");

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>UsingJs</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
  </head>

  <body>
    <div class='container' style='margin:10px;'>
      <%= yield %>
    </div>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
  </body>
</html>